language: ruby

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      rvm: system
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gem

install: true # skip install step

before_script:
  - . ci/travis/before_script.sh

script:
  - . ci/travis/script.sh

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
